version: '3.7'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - 4000:4000
    depends_on:
      - db
    links:
      - db:db
  db:
    image: postgres:12.0-alpine
    ports:
      - 5432:5432
    volumes:
      - /tmp/postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=codingmarket
      - POSTGRES_DB=codingtutorials_db
  # frontend:
  #   build: ./frontend
  #   volumes:
  #     - ./frontend:/app
  #   ports:
  #     - 3000:3000
